<?php
/**
 * Localized data
 *
 * @copyright   Copyright (C) 2013 XXXXX
 * @license     http://opensource.org/licenses/AGPL-3.0
 */
// Contact class
Dict::Add('FR FR', 'French', 'Français', array(
	'Class:Contact/Attribute:project_list' => 'Projets sur lesquels je travaille',
	'Class:Contact/Attribute:projects_list' => 'Porjets',
	'Class:Contact/Attribute:wbs_list' => 'Livrables pour lesquels je suis impliqué',
	'Class:Contact/Attribute:wbss_list' => 'Livrables',
	'Class:Contact/Attribute:wbss_list+' => 'Livrables sur lesquels je travaille',
	'Class:Contact/Tab:PMP' => 'Projets et livrables',
	'Class:Contact/Tab:PMP+' => 'Projets et livrables sur lesquels je travaille',
	'Class:lnkContactToProject' => 'Lien Contact / Projet',
	'Class:lnkContactToProject/Attribute:contact_id' => 'Contact',
	'Class:lnkContactToProject/Attribute:project_id' => 'Projet',
	'Class:lnkContactToProject/Attribute:role/Value:1' => 'Client',
	'Class:lnkContactToProject/Attribute:role/Value:2' => 'Ressource',
	'Class:lnkContactToProject/Name' => '%1$s - %2$s',
	'Class:lnkContactToTicket/Attribute:allocated_days' => 'Jours alloués',
	'Class:lnkContactToTicket/Attribute:allocated_percent' => '% alloué',
	'Class:lnkContactToTicket/Attribute:category' => 'Responsabilité',
	'Class:lnkContactToTicket/Attribute:category/Value:1' => 'Client',
	'Class:lnkContactToTicket/Attribute:category/Value:2' => 'Ressource',
	'Class:lnkContactToTicket/Attribute:influence' => 'Influence',
	'Class:lnkContactToTicket/Attribute:influence/Value:objector' => 'Résistant',
	'Class:lnkContactToTicket/Attribute:influence/Value:partner' => 'Volontaire',
	'Class:lnkContactToTicket/Attribute:influence+' => 'Comportement vis à vis du projet',
	'Class:lnkContactToTicket/Attribute:power/Value:low' => 'Faible',
	'Class:lnkContactToTicket/Attribute:power/Value:strong' => 'Elevé',
	'Class:lnkContactToWBS' => 'Lien Contact / WBS',
	'Class:lnkContactToWBS/Attribute:allocated_days' => 'Jours alloués',
	'Class:lnkContactToWBS/Attribute:allocated_percent' => '% alloué',
	'Class:lnkContactToWBS/Attribute:category/Value:1' => 'Client',
	'Class:lnkContactToWBS/Attribute:category/Value:2' => 'Ressources',
	'Class:lnkContactToWBS/Attribute:contact_id' => 'Intervenants',
	'Class:lnkContactToWBS/Attribute:influence/Value:objector' => 'Résistant',
	'Class:lnkContactToWBS/Attribute:influence/Value:partner' => 'Volontaire',
	'Class:lnkContactToWBS/Attribute:power/Value:low' => 'Faible',
	'Class:lnkContactToWBS/Attribute:power/Value:strong' => 'Elevé',
	'Class:lnkContactToWBS/Attribute:wbs_id' => 'Livrables',
	'Class:lnkContactToWBS/Name' => '%1$s - %2$s',
));

// Project class
Dict::Add('FR FR', 'French', 'Français', array(
	'Class:Project' => 'Projet',
	'Class:Project/Attribute:agent_id' => 'Chef de projet',
	'Class:Project/Attribute:allocatedtimes_list' => 'Temps alloué',
	'Class:Project/Attribute:calculated_end_date' => 'Date de fin du dernier livrable',
	'Class:Project/Attribute:calculated_end_date+' => 'La date de fin du dernier livrable est considérée',
	'Class:Project/Attribute:caller_id' => 'Sponsor',
	'Class:Project/Attribute:constraints' => 'Contraintes',
	'Class:Project/Attribute:contacts_list' => 'Parties Prenantes',
	'Class:Project/Attribute:contacts_list+' => 'Contacts impliqués sur le projet',
	'Class:Project/Attribute:projectchanges_list' => 'Changement sur Projet',
	'Class:Project/Attribute:projectchanges_list_displaybare' => 'Changement sur projet  non clos ni rejeté ou lié à un livrable non clos',
	'Class:Project/Attribute:risks_costs' => 'Coûts des risques',
	'Class:Project/Attribute:risks_list' => 'Risques ',
	'Class:Project/Attribute:risks_list_displaybare' => 'Risques non clos ni rejetés, dont la stratégie de réponse n\'est ni le transfert ni l\'évitement ',
	'Class:Project/Attribute:status' => 'Statut',
	'Class:Project/Attribute:status/Value:cancelled' => 'Annulé',
	'Class:Project/Attribute:status/Value:closed' => 'Clôturé',
	'Class:Project/Attribute:status/Value:executed' => 'En cours d\'exécution',
	'Class:Project/Attribute:status/Value:initiated' => 'Initialisation',
	'Class:Project/Attribute:status/Value:monitored' => 'Suivi/maitrise',
	'Class:Project/Attribute:status/Value:planned' => 'Planifié',
	'Class:Project/Attribute:team_id' => 'Equipe de projet',
	'Class:Project/Attribute:title' => 'Titre',
	'Class:Project/Attribute:wbs_cost' => 'Coûts des livrables',
	'Class:Project/Attribute:wbs_costs' => 'Coûts des livrables',
	'Class:Project/Attribute:wbss_list' => 'Livrables',
	'Class:Project/Attribute:wbss_list_displaybare' => 'Livrables non clos',
	'Class:Project/Name' => '%1$s-%2$s',
	'Class:Project/Stimulus:ev_cancel' => 'Annuler',
	'Class:Project/Stimulus:ev_close' => 'Clôturer',
	'Class:Project/Stimulus:ev_execute' => 'Exécuter',
	'Class:Project/Stimulus:ev_monitor' => 'Surveiller avant clôture',
	'Class:Project/Stimulus:ev_monotir' => 'To monitor',
	'Class:Project/Stimulus:ev_plan' => 'Planifier',
	'Class:Project/Stimulus:ev_reexecute' => 'Revenir à l\'exécution',
	'Class:Project/Tab:Summary' => 'Vue d\'ensemble',
	'Class:Project/Tab:Summary+' => 'Vue d\'ensemble du projet',
	'Class:Project:Display:accepted_risks' => 'Coûts des risques "acceptés"',
	'Class:Project:Display:delivrables_costs' => 'Coûts des livrables',
	'Class:Project:Summary_costs' => 'Information sur les coûts',
	'Class:Project:Summary_general' => 'Informations générales',
	'Project:Budget' => 'Coûts',
	'Project:Contacts' => 'Contacts',
	'Project:Costs' => 'Coûts',
	'Project:Dates' => 'Dates',
	'Project:Details' => 'Détails',
	'Project:Display:delivrables_costs' => 'Coûts des livrables',
	'Project:Error:EndDateMustBeGreaterThanStartDate' => 'La date de fin doit être supérieure à la date de début',
	'Project:Error:ProjectEndDateMustBeGreaterThanWBSEndDate' => 'La date de fin du projet doit être supérieure à la date de fin du dernier livrable',
	'Project:GeneralInfo' => 'Information',

	'Menu:MyProject' => 'Mes projets',
	'Menu:MyProject+' => 'Mes projets en tant que chef de projet',
	'Menu:NewProject' => 'Nouveau projet',
	'Menu:Overview' => 'Vue d\'ensemble',
	'Menu:Project:Overview' => 'Vue d\'ensemble',
	'Menu:ProjectChangeMenu' => 'Changement sur projet',
	'Menu:ProjectManagement' => 'Gestion des projets',
	'Menu:ProjectMenu' => 'Gestion des projets',
	'Menu:SearchProject' => 'Rechercher des projets',
	'UI:AddLinkedObjectsOf_Class' => 'Ajouter %1$s',
	'UI:ProjectMgmtMenuOverview:Title' => 'Dashboard',
	'UI-IssueManagementOverview-OpenIssueByProject' => 'Risques avérés ouverts par client',
	'UI-ProjectManagementOverview-Last-12Months' => 'Projets des 12 derniers mois ( par date de début de projet)',
	'UI-ProjectManagementOverview-Last-3Months' => 'Projets des 3 derniers mois (par client)',
	'UI-ProjectManagementOverview-OpenProjectByStatus' => 'Projets ouverts par statut',

));

// WBS class
Dict::Add('FR FR', 'French', 'Français', array(
	'Class:WBS' => 'Livrable',
	'Class:WBS/Attribute:acceptance' => 'Critères d\'acceptation',
    'Class:WBS/Attribute:available_budget' => 'Budget',
    'Class:WBS/Attribute:completion' => '% accomplissement',
    'Class:WBS/Attribute:contacts_list' => 'Parties prenantes',
    'Class:WBS/Attribute:contacts_list_proj_displaybare' => 'Parties prenants attachées au projet',
    'Class:WBS/Attribute:contacts_list_wbs_displaybare' => 'Parties prenantes liés à des livrables non clos',
    'Class:WBS/Attribute:contacts_list+' => 'Contacts impliqués dans les livrables',
    'Class:WBS/Attribute:delay' => 'Délai',
    'Class:WBS/Attribute:description' => 'Description',
    'Class:WBS/Attribute:end_date' => 'Date de fin souhaitée',
    'Class:WBS/Attribute:freetime' => 'Temps restant jusqu\'à la date de fin',
    'Class:WBS/Attribute:labor_cost' => 'Coûts Homme',
    'Class:WBS/Attribute:material_cost' => 'Coûts Matériel',
    'Class:WBS/Attribute:name' => 'Nom',
    'Class:WBS/Attribute:project_id' => 'Projet',
    'Class:WBS/Attribute:re_estimated_end_date' => 'Date de fin évaluée',
    'Class:WBS/Attribute:re_estimated_start_date' => 'Date de début évaluée',
    'Class:WBS/Attribute:ref' => 'Référence',
    'Class:WBS/Attribute:start_date' => 'Date de début souhaitée',
    'Class:WBS/Attribute:status' => 'Statut',
    'Class:WBS/Attribute:status/Value:cancel' => 'Annulé',
    'Class:WBS/Attribute:status/Value:closed' => 'Livré/clos',
    'Class:WBS/Attribute:status/Value:pending_parent' => 'En attente du livrable parent',
    'Class:WBS/Attribute:status/Value:running' => 'En cours',
    'Class:WBS/Attribute:status+' => 'Status of WBS',
    'Class:WBS/Attribute:technical_info' => 'Informations techniques',
    'Class:WBS/Attribute:time_planned' => 'Temps estimé',
    'Class:WBS/Attribute:wbs_budget' => 'Budget',
    'Class:WBS/Attribute:wbs_cost' => 'Coût total',
    'Class:WBS/Attribute:wbs_log' => 'Log',
    'Class:WBS/Attribute:wbs_owner_id' => 'Responsable',
    'Class:WBS/Attribute:wbs_real_costs' => 'Coûts réels des livrables',
    'Class:WBS/Attribute:wbss_child_list' => 'Livrables enfants',
    'Class:WBS/Attribute:wbss_parent_list' => 'Livrables parents',
    'Class:WBS/Name' => '%1$s-%2$s',
    'Class:WBS/Stimulus:ev_cancel' => 'Cancel deliverable',
    'Class:WBS/Stimulus:ev_closed' => 'Closed',
    'Class:WBS/Stimulus:ev_reopen' => 'Re-open',
    'Class:WBS/Stimulus:ev_running_admin' => 'Activate child task',
    'Class:WBS+' => 'Liste des livrables en travaux de projet',
	'WBS:Cost'  =>  'Coûts',
	'WBS:Dates'  =>  'Dates',
	'WBS:Error:ParentCantBeChildren'  =>  'Vous ne pouvez pas être livrable parent de vous-mêmes',
	'WBS:Execution'  =>  'Exécution',
	'WBS:Info'  =>  'Information',

	'Class:lnkWBSToWBS'  =>  'Lien Livrable enfant / Livrable parent',
	'Class:lnkWBSToWBS/Attribute:child_wbs_id'  =>  'Livrable enfant ',
	'Class:lnkWBSToWBS/Attribute:parent_wbs_id'  =>  'Livrable parent',
	'Class:lnkWBSToWBS/Attribute:wbs_id'  =>  'Livrable parent',
	'Class:lnkWBSToWBS/Name'  =>  '%1$s - %2$s',

	'Menu:MyWBS'  =>  'Mes livrables',
	'Menu:MyWBS+'  =>  'Les livrables qui me sont assignés',
	'Menu:NewWBS'  =>  'Nouveau livrable',
	'Menu:WBSMenu'  =>  'Livrables',
	'Menu:SearchWBS'  =>  'Rechercher des livrables',
	'UI-WBSManagementOverview-OpenWBSByProject' => 'Livrables en cours par projet',
));















